version: 2
jobs:
  conda_4.2.12:
    environment:
      VER: 4.2.12
    docker:
      - image: continuumio/miniconda3:4.2.12
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: bash scripts/install-system.sh
      - run:
          name: Configure conda
          command: bash scripts/config-conda.sh
      - run:
          name: numpy from defaults
          command: |
            bash scripts/time.txt conda install -vv --quiet numpy
      - store_artifacts:
          path: time.txt
      - store_artifacts:
          path: log.txt
workflows:
  version: 2
  all:
    jobs:
      - conda_4.2.12

