version: 2

steps: &steps
  steps:
    - checkout
    - run:
        name: Install system dependencies
        command: bash scripts/install-system.sh
    - run:
        name: Configure conda
        command: bash scripts/config-conda.sh
    - run:
        name: numpy from defaults
        command: bash scripts/test-numpy-defaults.sh
    - run:
        name: numpy from conda-forge
        command: bash scripts/test-numpy-cf.sh
    - run:
        name: scikit-learn from defaults
        command: bash scripts/test-scikit-learn-defaults.sh
    - run:
        name: scikit-learn from conda-forge
        command: bash scripts/test-scikit-learn-cf.sh
    - run:
        name: r-base from defaults
        command: bash scripts/test-r-base-defaults.sh
    - run:
        name: r-base from conda-forge
        command: bash scripts/test-r-base-cf.sh
    - run:
        name: r-devtools from defaults
        command: bash scripts/test-r-devtools-defaults.sh
    - run:
        name: r-devtools from conda-forge
        command: bash scripts/test-r-devtools-cf.sh
    - run:
        name: bioconductor-biobase from bioconda
        command: bash scripts/test-bioconductor-biobase.sh
    - run:
        name: bioconductor-limma from bioconda
        command: bash scripts/test-bioconductor-limma.sh
    - run:
        name: r-workflowr from jdblischak
        command: bash scripts/test-r-workflowr-jdblischak.sh
    - run:
        name: bioconductor-scde from jdblischak
        command: bash scripts/test-bioconductor-scde-jdblischak.sh
    - store_artifacts:
        path: list/
        destination: list
    - store_artifacts:
        path: log/
        destination: log
    - store_artifacts:
        path: time/
        destination: time
    - persist_to_workspace:
        root: ./
        paths:
          - list/
          - log/
          - time/

jobs:
  conda_4.3.27p0:
    <<: &steps
    environment:
      VER: 4.3.27p0
    docker:
      - image: continuumio/miniconda3:4.3.27p0

  conda_4.4.10:
    <<: &steps
    environment:
      VER: 4.4.10
    docker:
      - image: continuumio/miniconda3:4.4.10

#  conda_4.5.12:
#    environment:
#      VER: 4.5.12
#    docker:
#      - image: continuumio/miniconda3:4.5.12
#    steps:
#      <<: *setup
#      <<: *tests
#      <<: *store
#
#  conda_latest_release:
#    environment:
#      VER: latest_release
#    docker:
#      - image: continuumio/miniconda3:latest
#    steps:
#      - *setup
#      - *release
#      - *tests
#      - *store
#
#  conda_latest_commit:
#    environment:
#      VER: latest_commit
#    docker:
#      - image: continuumio/miniconda3:latest
#    steps:
#      <<: *setup
#      - run:
#          name: Install latest conda
#          command: bash scripts/install-latest-conda.sh
#      <<: *tests
#      <<: *store

  report:
    docker:
      - image: continuumio/miniconda3:4.3.27p0
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Configure conda
          command: bash scripts/config-conda.sh
      - run:
          name: Install analysis packages
          command: |
            conda install -c conda-forge \
                          git \
                          r-base \
                          r-dplyr \
                          r-fs \
                          r-ggplot2 \
                          r-rmarkdown \
                          r-stringr
      - run:
          name: Build report
          command: |
            Rscript -e 'rmarkdown::render("index.Rmd")'
            mkdir -p docs/
            mv index.html docs/
      - add_ssh_keys:
          fingerprints:
            - "19:22:95:f8:08:e2:f5:0e:ef:47:d2:0e:1a:0b:96:5e"
      - run:
          name: Commit report
          command: |
            git status
            git config user.name CircleCI
            git config user.email CircleCI
            git add docs/index.html
            git commit -m "Update report [skip ci]"
            git status
            git remote -v
            git push origin master
      - store_artifacts:
          path: docs/
          destination: docs

workflows:
  version: 2
  all:
    jobs:
      - conda_4.3.27p0
      - conda_4.4.10
#      - conda_4.5.12
#      - conda_latest_release
#      - conda_latest_commit
      - report:
          requires:
            - conda_4.3.27p0
            - conda_4.4.10
#            - conda_4.5.12
#            - conda_latest_release
#            - conda_latest_commit

