version: 2
jobs:
  conda_4.2.12:
    docker:
      - image: continuumio/miniconda3:4.2.12
    steps:
      - checkout
      - run:
          name: System installation
          command: |
            apt-get update
            apt-get install --yes --no-install-recommends \
              time
      - run:
          name: conda setup
          command: bash scripts/config-conda.sh
      - run:
          name: numpy from defaults
          command: |
            /usr/bin/time -f "%e %U %S %P %M" -o time.txt conda install -vv --quiet numpy 2> log.txt
      - store_artifacts:
          path: time.txt
workflows:
  version: 2
  all:
    jobs:
      - conda_4.2.12

