version: 2
jobs:
  conda_4.1.11:
    docker:
      - image: continuumio/miniconda3:4.1.11
    steps:
      - checkout
      - run: apt-get update && apt-get install --yes time
      - run: /usr/bin/time -f "%e %U %S %P %M" -o time.txt conda install -vv numpy 2> log.txt
      - store_artifacts:
          path: time.txt
  conda_4.2.12:
    docker:
      - image: continuumio/miniconda3:4.2.12
    steps:
      - checkout
      - run: apt-get update && apt-get install --yes time
      - run: /usr/bin/time -f "%e %U %S %P %M" -o time.txt conda install -vv numpy 2> log.txt
      - store_artifacts:
          path: time.txt
workflows:
  version: 2
  all:
    jobs:
      - conda_4.1.11
      - conda_4.2.12

